<?php

namespace AllDigitalRewards\Xoxoday\Orders;

use AllDigitalRewards\Xoxoday\AbstractEntity;

class Voucher extends AbstractEntity
{
    protected int $productId;
    protected string $voucherCode;
    protected string $pin;
    protected string $validity;
    protected string $amount;
    protected string $currency;
    protected string|float $currencyValue;
    protected string $orderStatus;
    protected string $country;
    protected string $type;

    /**
     * @return int
     */
    public function getProductId(): int
    {
        return $this->productId;
    }

    /**
     * @param int $productId
     */
    public function setProductId(int $productId): void
    {
        $this->productId = $productId;
    }

    /**
     * @return string
     */
    public function getVoucherCode(): string
    {
        return $this->voucherCode;
    }

    /**
     * @param string $voucherCode
     */
    public function setVoucherCode(string $voucherCode): void
    {
        $this->voucherCode = $voucherCode;
    }

    /**
     * @return string
     */
    public function getPin(): string
    {
        return $this->pin;
    }

    /**
     * @param string $pin
     */
    public function setPin(string $pin): void
    {
        $this->pin = $pin;
    }

    /**
     * @return string
     */
    public function getValidity(): string
    {
        return $this->validity;
    }

    /**
     * @param string $validity
     */
    public function setValidity(string $validity): void
    {
        $this->validity = $validity;
    }

    /**
     * @return string
     */
    public function getAmount(): string
    {
        return $this->amount;
    }

    /**
     * @param string $amount
     */
    public function setAmount(string $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * @return string
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    /**
     * @param string $currency
     */
    public function setCurrency(string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * @return float|string
     */
    public function getCurrencyValue(): float|string
    {
        return $this->currencyValue;
    }

    /**
     * @param float|string $currencyValue
     */
    public function setCurrencyValue(float|string $currencyValue): void
    {
        $this->currencyValue = $currencyValue;
    }

    /**
     * @return string
     */
    public function getOrderStatus(): string
    {
        return $this->orderStatus;
    }

    /**
     * @param string $orderStatus
     */
    public function setOrderStatus(string $orderStatus): void
    {
        $this->orderStatus = $orderStatus;
    }

    /**
     * @return string
     */
    public function getCountry(): string
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry(string $country): void
    {
        $this->country = $country;
    }

    /**
     * @return string
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    public function toArray(): array
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
